src/by/gstu/atp/beans/Unit.java
package by.gstu.atp.beans;

import by.gstu.atp.interfaces.IBean;

public class Unit implements IBean {

	private long code;
	private String fullName;
	private String shortName;

	public Unit() { }

	public Unit(long code, String fullName, String shortName) {
		this.code = code;
		this.fullName = fullName;
		this.shortName = shortName;
	}

	public long getCode() {
		return code;
	}

	public void setCode(long code) {
		this.code = code;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Override
	public String[] getHeader() {
		return new String[] { "Код", "Полное наименование",
				"Краткое наименование" };
	}

	@Override
	public String[] getContent() {
		return new String[] { "" + getCode(), getFullName(), getShortName() };
	}

	@Override
	public String getHtmlValue() {
		return "" + getCode();
	}

	@Override
	public String getHtmlName() {
		return getFullName();
	}

	@Override
	public String[] getFields() {
		return new String[] { getFullName(), getShortName() };
	}

}

src/by/gstu/atp/controllers/OperationsController.java
package by.gstu.atp.controllers;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import by.gstu.atp.ConstantsPages;
import by.gstu.atp.enums.Operation;
import by.gstu.atp.enums.Page;
import by.gstu.atp.exceptions.DaoException;
import by.gstu.atp.helpers.Validator;
import by.gstu.atp.interfaces.AbstractController;
import by.gstu.atp.interfaces.IBean;
import by.gstu.atp.interfaces.IBeanDAO;

public class OperationsController extends AbstractController {

	private static final long serialVersionUID = 1L;

	@Override
	protected void performTask(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		String strOp = request.getParameter("op");
		String[] strIds = request.getParameterValues("id");

		Operation op = Operation.convertFrom(strOp);
		IBean[] ids = Validator.checkIds(strIds);

		HttpSession session = request.getSession();
		Page page = (Page) session.getAttribute("page");

		try {
			IBeanDAO dao = page.getDao();
			switch (op) {
			case DEL:
				dao.delete(ids);
				break;

			case ADD:
				// NOP
				break;

			case EDIT:
				IBean bean = dao.get(ids[0].getCode());
				request.setAttribute("bean", bean);
				break;

			default:
				// NOP
				break;
			}

			forwardPage(ConstantsPages.MAIN_CONTROLLER, request, response);
		} catch (DaoException e) {
			jumpError(e.getMessage(), request, response);
		}
	}

}

WebContent/parts/content.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="/WEB-INF/c.tld" prefix="c"%>

<div class="container">
	<h3>
		<c:out value="${page.name}" />
	</h3>
	<table class="bordered hoverable table-fix">
		<thead>
			<tr>
				<th style="width: 2%"><a href="JavaScript: selectCB()"
					class="black-text" title="Выбрать все"><i
						class="small mdi-action-spellcheck"></i></a></th>
				<c:forEach var="headItem" items="${beans[0].header}">
					<th><c:out value="${headItem}" /></th>
				</c:forEach>
			</tr>
		</thead>
		<c:forEach var="bean" items="${beans}">
			<tr>
				<td><input type="checkbox" id="${bean.code}" name="id"
					value="${bean.code}" /><label for="${bean.code}"></label></td>
				<c:forEach var="contentItem" items="${bean.content}">
					<td><c:out value="${contentItem}" /></td>
				</c:forEach>
			</tr>
		</c:forEach>
	</table>
</div>

WebContent/parts/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<footer class="page-footer">
	<div class="footer-copyright">
		<div class="container">
			© 2014-2015 ГГТУ ИТ-42, Егор Семенченя & Максим Потапенко<a class="grey-text text-lighten-4 right"
				href="https://bitbucket.org/pairedprojects/atp_sem_8">Bitbucket</a>
		</div>
	</div>
</footer>

WebContent/parts/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<nav class="top-nav blue nav-fix" id="index-banner">
	<div class="container">
		<h2 class="header center-on-small-only top-nav-header-font">Редактор НСИ &#171;Гидроблок&#187;</h2>
	</div>
</nav>

WebContent/parts/main-content.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<div class="container main-container-fix">
	<div class="slider slider-fix ">
		<ul class="slides">
			<li><img src="resources/img/free_time.jpg">
				<div class="caption center-align caption-right">
					<h3 class="white-text text-accent-2">Всегда вовремя</h3>
				</div></li>
			<li><img src="resources/img/graph.jpg">
				<div class="caption left-align caption-left black-text">
					<h3>Быстро и эффективно</h3>
				</div></li>
			<li><img src="resources/img/acces.jpg">
				<div class="caption center-align">
					<h2>Доступ в любом месте</h2>
				</div></li>
		</ul>
	</div>
</div>

WebContent/parts/menu.jsp
<%@page import="by.gstu.atp.enums.Page"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="/WEB-INF/c.tld" prefix="c"%>

<div class="container">
	<a href="#" data-activates="nav-mobile" class="button-collapse top-nav"><i
		class="mdi-navigation-menu"></i></a>
</div>
<ul id="nav-mobile" class="side-nav fixed">
	<li class="logo logo-fix"><a id="logo-container-fix" href="JavaScript: setPage('<%=Page.MAIN%>')"
		class="brand-logo" href="#"><img src="resources/icons/logo.png"
			height="100"></a></li>
	<li class="no-padding">
		<ul class="collapsible collapsible-accordion">
			<li class="bold"><a
				class="collapsible-header  waves-effect waves-teal menu-font-fix">Справочники</a>
				<div class="collapsible-body">
					<ul>
						<li><a href="JavaScript: setPage('<%=Page.PRODUCT_KINDS%>')">Виды продукции</a></li>
						<li><a href="JavaScript: setPage('<%=Page.PRODUCT_TYPES%>')">Типы продукции</a></li>
						<li><a href="JavaScript: setPage('<%=Page.PRODUCT_FEATURES%>')">Признаки продукции</a></li>
						<li><a href="JavaScript: setPage('<%=Page.PRODUCT_NAMES%>')">Наименования</a></li>
						<li><a href="JavaScript: setPage('<%=Page.MATERIALS%>')">Материалы</a></li>
						<li><a href="JavaScript: setPage('<%=Page.APPLICATION_RATES%>')">Нормы расхода</a></li>
						<li><a href="JavaScript: setPage('<%=Page.UNITS%>')">Единицы измерения</a></li>
					</ul>
				</div></li>
			<li class="bold"><a
				class="collapsible-header  waves-effect waves-teal menu-font-fix">Разузлование</a>
				<div class="collapsible-body">
					<ul>
						<li><a href="JavaScript: setPage('<%=Page.COMPOSITE%>')">Состав изделий</a></li>
						<li><a href="<c:url value='/search-detail'/>">Поиск</a></li>
					</ul>
				</div></li>
		</ul>
	</li>
</ul>
<form name="setPageForm" method="GET" action="<c:url value='/main'/>">
	<input type="hidden" name="page" value="" />
</form>

WebContent/parts/modal.jsp
<%@page import="by.gstu.atp.enums.Page"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="/WEB-INF/c.tld" prefix="c"%>
<%@ taglib uri="/WEB-INF/fn.tld" prefix="fn"%>

<c:if test="${not empty jspMessage}">
	<script>
		window.onload = function() {
			$("#addBtn").click();
		}
	</script>
</c:if>

<c:if test="${not empty bean}">
	<script>
		window.onload = function() {
			$("#editBtn").click();
		}
	</script>
</c:if>

<div id="addModal" class="modal">
	<div class="modal-header green">
		<div class="container modal-container-fix white-text">
			<h5>Добавление записи</h5>
		</div>
	</div>
	<div class="modal-content">
		<div class="row">
			<c:if test="${not empty jspMessage}">
				<p class="alert alert-error">
					<c:out value="${jspMessage}" />
				</p>
			</c:if>
			<form class="col s12" id="addFormId" name="addForm" method="POST"
				action="<c:url value='/add'/>">
				<div class="col s6">
					<c:forEach var="htmValue" items="${mValues}">
						<c:if test="${htmValue.type eq 'text'}">
							<div class="input-field col s12 s6-fix">
								<input id="${htmValue.name}" name="${htmValue.htmlName}"
									type="text" class="validate" /> <label for="${htmValue.name}">${htmValue.name}</label>
							</div>
						</c:if>
					</c:forEach>
				</div>
				<div class="col s6">
					<c:forEach var="htmValue" items="${mValues}">
						<c:if test="${htmValue.type eq 'select'}">
							<div class="input-field col s12 s6-fix">
								<select name="${htmValue.htmlName}">
									<option value="" disabled selected>${htmValue.name}</option>
									<c:forEach var="option" items="${htmValue.values}">
										<option value="${option.htmlValue}">${option.htmlName}</option>
									</c:forEach>
								</select>
							</div>
						</c:if>
					</c:forEach>
				</div>
			</form>
		</div>
	</div>
	<div class="modal-footer modal-footer-fix">
		<a class="waves-effect waves-red btn-flat modal-action modal-close">Отмена</a>
		<button onclick="document.addForm.submit()"
			class="waves-effect waves-green btn-flat modal-action">Добавить</button>
	</div>
</div>

<div id="editModal" class="modal">
	<div class="modal-header orange">
		<div class="container modal-container-fix white-text">
			<h5>Редактирование записи</h5>
		</div>
	</div>
	<div class="modal-content">
		<div class="row">
			<c:if test="${not empty jspMessage}">
				<p class="alert alert-error">
					<c:out value="${jspMessage}" />
				</p>
			</c:if>
			<form class="col s12" name="editForm" method="POST"
				action="<c:url value='/edit'/>">
				<input type="hidden" name="beanId" value="${bean.code}">
				<div class="col s6">
					<c:forEach var="i" begin="0" end="${page.length - 1}">
						<c:if test="${mValues[i].type eq 'text'}">
							<div class="input-field col s12 s6-fix">
								<input id="${mValues[i].name}" name="${mValues[i].htmlName}"
									type="text" class="validate" value="${bean.fields[i]}" /> <label
									for="${mValues[i].name}">${mValues[i].name}</label>
							</div>
						</c:if>
					</c:forEach>
				</div>
				<div class="col s6">
					<c:forEach var="i" begin="0" end="${page.length - 1}">
						<c:if test="${mValues[i].type eq 'select'}">
							<div class="input-field col s12 s6-fix">
								<select name="${mValues[i].htmlName}">
									<option value="" disabled>${mValues[i].name}</option>
									<c:forEach var="option" items="${mValues[i].values}">
										<c:set var="pValue" value="${fn:trim(option.htmlValue)}" />
										<c:set var="bValue" value="${fn:trim(bean.fields[i])}" />
										<c:if test="${pValue ne bValue}">
											<option value="${option.htmlValue}">${option.htmlName}</option>
										</c:if>
										<c:if test="${pValue eq bValue}">
											<option value="${option.htmlValue}" selected>${option.htmlName}</option>
										</c:if>
									</c:forEach>
								</select>
							</div>
						</c:if>
					</c:forEach>
				</div>
			</form>
		</div>
	</div>
	<div class="modal-footer modal-footer-fix">
		<a class="waves-effect waves-red btn-flat modal-action modal-close">Отмена</a>
		<button onclick="document.editForm.submit()"
			class="waves-effect waves-green btn-flat modal-action">Сохранить</button>
	</div>
</div>

<div id="deleteModal" class="modal">
	<div class="modal-header red">
		<div class="container modal-container-fix white-text">
			<h5>Удаление записи</h5>
		</div>
	</div>
	<div class="modal-content container">
		<p class="modal-text">
			Вы действительно хотите удалить запись(и)?
		</p>
	</div>
	<div class="modal-footer modal-footer-fix">
		<a class="waves-effect waves-red btn-flat modal-action modal-close">Нет</a>
		<button onclick="JavaScript: checkCB('del')"
			class="waves-effect waves-green btn-flat modal-action">Да</button>
	</div>
</div>

WebContent/parts/operations.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<div id="toTop" class="go-button go-up" title="Вверх">
	<a
		class="btn-floating btn-large waves-effect waves-light  pink accent-3"><i
		class="large mdi-hardware-keyboard-arrow-up"></i></a>
</div>

<div class="optional-panel">
	<div class="row row-fix" title="Добавить запись">
		<a id="addBtn"
			class="btn-floating btn-large waves-effect waves-light green modal-trigger"
			href="#addModal"><i class="large mdi-content-add"></i></a>
	</div>

	<div class="row row-fix" title="Изменить запись">
		<a
			class="btn-floating btn-large waves-effect waves-light orange modal-trigger"
			href="JavaScript: checkCB('edit')"><i
			class="large mdi-editor-mode-edit"></i></a> <a id="editBtn"
			class="modal-trigger" href="#editModal"></a>
	</div>

	<div class="row row-fix" title="Удалить запись">
		<a href="JavaScript: checkCbForDelete()"
			class="btn-floating btn-large waves-effect waves-light red modal-trigger"><i
			class="large mdi-content-clear"></i></a> <a id="deleteBtn"
			class="modal-trigger" href="#deleteModal"></a>
	</div>
</div>

<div id="toBottom" class="go-button go-down" title="Вниз">
	<a
		class="btn-floating btn-large waves-effect waves-light  pink accent-3"><i
		class="large mdi-hardware-keyboard-arrow-down"></i></a>
</div>

WebContent/parts/search-content.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="/WEB-INF/c.tld" prefix="c"%>

<div class="container">
	<h3>
		<br /> Поиск бракованной детали
	</h3>

	<ul id="details" class="dropdown-content dropdown-content-fix">
		<c:forEach var="item" items="${items}">
			<li><a href="JavaScript: setDetail('${item.code}')"
				id="${item.name}">${item.htmlName}<span class="badge">${item.code}</span></a></li>
		</c:forEach>
	</ul>
	<a class="btn dropdown-button pink darken-3" style="width: 500px;"
		href="#!" data-activates="details">Наименование детали <i
		class="mdi-navigation-arrow-drop-down right"></i>
	</a>

	<c:if test="${not empty beans}">
		<table class="bordered hoverable table-fix">
			<thead>
				<tr>
					<th>Наименование СЕ/Изделия</th>
					<th>Количество деталей <c:out value="${detail.name}" />,
						входящих в СЕ/Изделие
					</th>
				</tr>
			</thead>
			<c:forEach var="bean" items="${beans}">
				<tr>
					<td><c:out value="${bean.main.name}" /></td>
					<td><c:out value="${bean.count}" /></td>
				</tr>
			</c:forEach>
		</table>

		<br />
		<a class="waves-effect waves-light pink darken-3 btn right"
			href="JavaScript: setDetail('-1')"><i
			class="mdi-action-description right"></i>Получить ведомость</a>
	</c:if>
</div>

<form name="detailForm" method="GET"
	action="<c:url value='/search-detail'/>">
	<input type="hidden" name="code" value="" />
</form>